config/routes.rb
# Rails.application.routes.draw do
#   devise_for :users
#   #provides routes for the user controller 
#  resources :items do
#     member do 
#       patch :complete
#       # :complete refers to the complete method in the items controller
#     end
#   end
#  # provides routes for the items controller
#  root 'items#index'
#  #root route. controller to index action
# end
Rails.application.routes.draw do
  devise_for :users
  resources :items do
    member do
      patch :complete
    end
  end
  root 'items#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user

  def completed?
    !completed_at.blank?
    # meaning, an item is completed, if the completed_at attribute is not blank
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :items 
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery with: :null_session
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :find_item, only: [:show, :edit, :update, :destroy]
  
  def index
    if user_signed_in?
    @items = Item.where(:user_id => current_user.id).order("created_at DESC")
    end
    #now only the items that a specific user creates will be displayed. 
  end
  
  def show
    # the item is already available cause of the before_action
  end
  
  def new
    @item = current_user.items.build
    #now when a new item is created, it is attached to the current user    
  end
  
  def create
    #now when a new item is created, it is attached to the current user    
    @item = current_user.items.build(item_params)
    if @item.save
      redirect_to root_path
    else
      render 'new' 
      # rendering a new form
    end
    #remember that create happens in the new view
  end

  def edit
    # the item is already available cause of the before_action
  end

  def update
    # the item is already available cause of the before_action
    if @item.update(item_params)
      redirect_to item_path(@item)
      #line 30's argument is the new updated info and the redirect_to is to the show path with respect to the current item.
    else
      render 'edit'
    end
    #remember update happens in the edit view
  end

  def destroy

    @item.destroy
    redirect_to root_path   
  end

  def complete
    @item = Item.find(params[:id])
    @item.update_attribute(:completed_at, Time.now)
    redirect_to root_path, notice: "Item successfully completed!"
  end

  private 

    def item_params
      params.require(:item).permit(:title, :description) 
    end

    def find_item
      @item = Item.find(params[:id])
      
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/items/_form.html.erb
<%= simple_form_for @item do |f| %>
  <%= f.input :title, label: "Item" %>
  <!-- for every item, an input tag is being created...:title is related to the table attribute...label is the name of the input -->
  <%= f.input :description %>
  <%= f.button :submit %>
<% end %> 
<!-- no equal sign here -->

app/views/items/edit.html.erb
<div class="col-md-6 col-md-offset-3">
  <h1>Edit Item</h1>

  <%= render 'form' %>
  <!-- the form will already be filled out and ready for edit, if needed -->
</div>

app/views/items/index.html.erb
<% if user_signed_in? %>
  <div class="col-md-6 col-md-offset-3">
    <% @items.each do |item| %>
    <% if item.completed? %>

      <div class="row item">
        <div class="col-md-8">
          <h2 style="opacity: 0.5;" class="item-title"><strike><%= link_to item.title, item %></strike></h2>
          <p style="opacity: 0.5;" class="item-desc item-sub-title"><%= item.description %></p>
          <p style="opacity: 0.5;" class="time-ago item-sub-title">Completed <%=time_ago_in_words(item.completed_at) %> ago</p>
        </div>

        <div class="col-md-2">
          <%= link_to complete_item_path(item), method: :patch do %>
          <i class="fa fa-lg fa-check"></i>
            <%end%>
        </div>

        <div class="col-md-2">
          <%= link_to item, method: :delete, data: {confirm: "are you sure?"} do %>
          <i class="fa fa-lg fa-trash"></i>
            <%end%>
        </div>

      </div>

    <%else%>

    <div class="row item">

      <div class="col-md-8">
        <h2 class="item-title"><%= link_to item.title, item %></h2>
        <p class="item-desc item-sub-title"><%= item.description %></p>
        <p class="time-ago item-sub-title">Created <%=time_ago_in_words(item.created_at) %> ago</p>
      </div>

      <div class="col-md-2">
        <%= link_to complete_item_path(item), method: :patch do %>
          <i class="fa fa-lg fa-check"></i>
            <%end%>
      </div>

      <div class="col-md-2">
        <%= link_to item, method: :delete, data: {confirm: "are you sure?"} do %>
          <i class="fa fa-lg fa-trash"></i>
          <%end%>
      </div>

    </div>
     <%end%>
    <% end %> 
  </div>
<% else %>
  <% render 'layouts/static_page' %> 
<% end %>

app/views/items/new.html.erb
<div class="col-md-6 col-md-offset-3">
  <h1>new item</h1>
  <%= render 'form' %> 
</div>

app/views/items/show.html.erb
<div class="col-md-6 col-md-offset-3"> 
  <h2><%= @item.title %></h2>
  <p><%= @item.description %></p>

  <%= link_to "Back", root_path%>
  <%= link_to "Edit", edit_item_path(@item)%>
</div>

app/views/layouts/_static_page.html.erb
<div class="jumbotron">
  <h1>Welcome</h1>
  <p>Keep track of your items</p>
  <% link_to "Sign up", new_user_registration_path, class: "btn btn-primary" %>
  <% link_to "Log In", new_user_session_path, class: "btn btn-primary" %> 
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CheckList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <script src="https://kit.fontawesome.com/959f0f6a88.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <nav class="navbar navbar-default">
      <div class="container">
        <div class="navbar-header">
          <%= link_to "CheckList", root_path, class: "navbar-brand" %>
        </div>
        <ul class="nav navbar-nav">
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
          <% if current_user.present? %>
            <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
          <% else %> 
            <li><%= link_to "Log In", new_user_session_path %></li>
          <% end %>
        </ul>
        <% if user_signed_in? %>
          <%= link_to "New Item", new_item_path, class: "navbar-text navbar-link navbar-right" %>
        <% end %>
      </div>
    </nav> 
    <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
    <div class="container">
      <%= yield %>
    </div>
    <!-- this is where all the views get inserted to display to the user. any html markup outside of the yield tag is going to be common for all the views.   -->
  </body>
</html>